server:
  port: 8000
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/*****?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: "****"

  data:
    redis:
      host: "***.**.**.**"
      password:
      port: 0000

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml

logging:
  level:
    com.dao: debug